version: '3'

services:
  reverse_proxy:
    image: traefik
    network_mode: host
    command:
    - --api.insecure=true
    - --providers.docker=true
    - --entrypoints.web.address=:80
    - --entrypoints.traefik.address=:9090
    - --accessLog
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock:ro
    labels:
    - traefik.http.routers.ui.rule=Host(`ori-rando.localhost`)
    - traefik.http.routers.ui.service=ui
    - traefik.http.services.ui.loadbalancer.server.url=http://127.0.0.1:3000
    - traefik.http.services.ui.loadbalancer.server.port=3000
    - traefik.http.routers.api.rule=Host(`ori-rando.localhost`) && PathPrefix(`/api`)
    - traefik.http.routers.api.service=api
    - traefik.http.services.api.loadbalancer.server.url=http://127.0.0.1:8080
    - traefik.http.services.api.loadbalancer.server.port=8080
