name: electron

on:
  push:
    branches:
    - '*'

jobs:
  electron:
    runs-on: windows-2019
    steps:
    - name: Checkout 🛎
      uses: actions/checkout@master

    - uses: actions/setup-node@v3
      with:
        node-version: 16
        cache: 'npm'
        cache-dependency-path: '**/package-lock.json'

    - run: npm ci

    - name: Generate client
      run: |
        $env:API_HOST = "${{ github.event.inputs.api_host || 'dev.wotw.orirando.com' }}"
        $env:API_SECURE = "true"
        $env:IS_ELECTRON = "true"
        yarn generate
        copy .\dist\* .\electron\public\

    - name: Build electron
      working-directory: .\\electron
      run: |
        npm ci
        npm run electron:build -w
    - name: Archive artifacts
      uses: actions/upload-artifact@v2
      with:
        name: launcher
        retention-days: 1
        path: |
          .\electron\dist_electron\win-unpacked\*
